from bs4 import BeautifulSoup
import requests 
import re 
import random

URL = "https://en.wikipedia.org/w/api.php"

HEADERS = {"User-Agent": "CS50WikiGame/1.0 (anaelmumtaz15@gmail.com)"}

def get_wikipedia_page(title):
    PARAMS = {
        "action": "parse", #Gets the HTML of a page
        "page": title , #This is the page's title
        "prop": "text", #Removes extra info 
        "format": "json", #The response will be a json dictionary 
        "redirects": 1, #Does the redirects
    }

    try:
        response = requests.get(URL, headers=HEADERS, params=PARAMS)
        response.raise_for_status()

        data = response.json() 
        '''The format of data is this: {
                                        "parse": {
                                            "title": "Python (programming language)",
                                            "pageid": 23862,
                                            "text": {"*": "<div class=\"mw-parser-output\"><p><b>Python</b> is a high-level...</p></div>"}
                                        }'''

        #checking to make sure page exists
        if "error" in data:
            print(f"API ERROR: {data['error']['info']}")
            return None

        pagetitle = data["parse"]["title"]
        rawhtml = data["parse"]["text"]["*"]

        return pagetitle, rawhtml

    except requests.exceptions.RequestException as e:
        print(f"Network Error: {e}")
        return None

def clean_page(raw_html):
    if not raw_html:
        return 
    soup = BeautifulSoup(raw_html, "html.parser") #converting the whole html into a soup format
    clutter_classes = [".infobox", ".navbox", ".reflist", ".reference", ".mw-editsection", ".metadata"] #tags we wanna remove
 
    for selector in clutter_classes: #loop to go over each of the clutters
        for element in soup.select(selector): #find the clutter in the html
            element.decompose() #delete it

    for a_tag in soup.find_all("a", href=True): #finding all links
        href = a_tag["href"]

        if (href.startswith("/wiki/") or href.startswith("./")) and ":" not in href: #swapping out the wiki href with my apps /play 
            if href.startswith("/wiki/"):
                article_name = href[6:]
            else:
                article_name = href[2:]    

            a_tag["href"] = f"/play?title={article_name}"
        else: 
            del a_tag["href"] #if any other kind of link, just making it plain text
            a_tag.name = "span" 

    return str(soup)    #returning the cleaned html


def random_page():
    '''changing my approach with the random pages. I was initially doing this with the random option in wikipedia api but it 
    gives niche pages too often. I now have generated a list of 100 most popular wikipedia pages (using Google's Gemini). I wil
    use random function on the index of the list to get two random pages.
    '''
    POPULAR_WIKIPEDIA_PAGES = [ 
    #Generated by Gemini
    # Geography & Countries (35)
    "United States",
    "United Kingdom",
    "India",
    "China",
    "Japan",
    "France",
    "Germany",
    "Canada",
    "Australia",
    "Brazil",
    "Russia",
    "Italy",
    "Spain",
    "Mexico",
    "Egypt",
    "South Africa",
    "Argentina",
    "Greece",
    "Turkey",
    "New York City",
    "London",
    "Paris",
    "Tokyo",
    "Rome",
    "Beijing",
    "Cairo",
    "Sydney",
    "Los Angeles",
    "Berlin",
    "Moscow",
    "Toronto",
    "Mumbai",
    "Seoul",
    "Istanbul",
    "Antarctica",

    # History & Major Eras (25)
    "World War I",
    "World War II",
    "Industrial Revolution",
    "Renaissance",
    "Ancient Egypt",
    "Roman Empire",
    "Cold War",
    "Middle Ages",
    "American Revolution",
    "French Revolution",
    "Byzantine Empire",
    "Ottoman Empire",
    "Great Depression",
    "Age of Enlightenment",
    "Classical antiquity",
    "Stone Age",
    "Bronze Age",
    "Space Race",
    "Apollo 11",
    "Silk Road",
    "Globalization",
    "British Empire",
    "Mongol Empire",
    "Scientific Revolution",
    "American Civil War",

    # Key Historical Figures (35)
    "Albert Einstein",
    "Isaac Newton",
    "William Shakespeare",
    "Leonardo da Vinci",
    "Aristotle",
    "Plato",
    "Alexander the Great",
    "Julius Caesar",
    "Napoleon",
    "Abraham Lincoln",
    "Winston Churchill",
    "George Washington",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Charles Darwin",
    "Stephen Hawking",
    "Steve Jobs",
    "Bill Gates",
    "Galileo Galilei",
    "Nikola Tesla",
    "Thomas Edison",
    "Marie Curie",
    "Wolfgang Amadeus Mozart",
    "Ludwig van Beethoven",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Michelangelo",
    "Socrates",
    "Charles III",
    "Cleopatra",
    "Queen Victoria",
    "Elizabeth II",
    "Franklin D. Roosevelt",
    "Martin Luther King Jr.",
    "Mark Twain",

    # Sciences & Nature (35)
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Astronomy",
    "Computer science",
    "Artificial intelligence",
    "Earth",
    "Sun",
    "Moon",
    "Solar System",
    "Evolution",
    "Gravity",
    "DNA",
    "Electricity",
    "Thermodynamics",
    "Quantum mechanics",
    "Geology",
    "Psychology",
    "Ecology",
    "Milky Way",
    "Black hole",
    "Mars",
    "Water",
    "Climate change",
    "Ocean",
    "Atmosphere of Earth",
    "Photosynthesis",
    "Cell (biology)",
    "Genetics",
    "Atom",
    "Light",
    "Energy",
    "Periodic table",
    "Human body",

    # Technology & Global Organizations (20)
    "Internet",
    "Google",
    "Apple Inc.",
    "Microsoft",
    "NASA",
    "United Nations",
    "Wikipedia",
    "YouTube",
    "Facebook",
    "World Health Organization",
    "European Union",
    "NATO",
    "International Space Station",
    "World Wide Web",
    "Software",
    "Smartphone",
    "Automobile",
    "Aviation",
    "Rail transport",
    "Artificial satellite",

    # Arts, Culture, Media & Sports (25)
    "Music",
    "Cinema",
    "Literature",
    "Architecture",
    "The Beatles",
    "Michael Jackson",
    "Taylor Swift",
    "Star Wars",
    "Harry Potter",
    "Video game",
    "Olympic Games",
    "FIFA World Cup",
    "Academy Awards",
    "Marvel Cinematic Universe",
    "Basketball",
    "Association football",
    "Chess",
    "Television",
    "Radio",
    "Photography",
    "Animation",
    "Theatre",
    "Rock music",
    "Jazz",
    "Hip hop music",

    # General Knowledge & Society (25)
    "Language",
    "Money",
    "Food",
    "Agriculture",
    "Transport",
    "Medicine",
    "Philosophy",
    "History",
    "Art",
    "Sport",
    "Science",
    "Education",
    "Economics",
    "Democracy",
    "Law",
    "Government",
    "Religion",
    "Culture",
    "Poetry",
    "Novel",
    "Mythology",
    "Engineering",
    "Communication",
    "Geography",
    "Sociology"
    ] #This list has total 200 indexes.

    r = random.randint(0,200)

    return POPULAR_WIKIPEDIA_PAGES[r]
    
def normalize(text): #To make the titles same
        if not text:
            return ""
        text = str(text).replace("_", " ").replace("–", "-").replace("-", " ")
        return re.sub(r'\s+', ' ', text).strip().lower()
